### ISSUE TITLE
Macad agent scripts running out of resouces

### ISSUE THREAD

**Issue by AizazSharif** [praveen-palanisamy/macad-agents#10]
Hi @praveen-palanisamy @SHITIANYU-hue,

I am trying to run an [impala agent independent](https://github.com/praveen-palanisamy/macad-agents/blob/c7e48dd3dd1b9ce10dd5d52fc940300e3e328d67/src/macad_agents/rllib/impala_agent_independent.py#L312-L319) script to train multi-agents. My environment is working fine but all the scripts apparently create multiple Carla instances and it results in freezing my laptop. 
I took the screenshot to show the last logs on the terminal for reference.
![Screenshot from 2021-02-18 12-42-40](https://user-images.githubusercontent.com/9911205/108354787-3f1bbb00-71ea-11eb-9993-3f7eb950282d.png)

During this screenshot, around 3 to 4 windows get opened and it stucks my laptop unless I reboot.

Any help in this would be appreciated. 
Thanks

**Comment by praveen-palanisamy** [comment]
Hi @AizazSharif ,
The Deep RL Agent training does require quite a bit of compute resources especially given that the training environment (CARLA) itself needs a GPU to run. 
If you are running it on a laptop, please use the minimal number of rollout workers and learners using the `--num-workers`, `--num-envs-per-worker` and `--num-gpus` flags. You can set them all to `1` (if that's not what you are using as per the default).
