### ISSUE TITLE
`conda install numpy` won't finish forever

### ISSUE THREAD

**Issue by rsuwa** [praveen-palanisamy/macad-agents#18]
### Discussed in https://github.com/praveen-palanisamy/macad-agents/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **rsuwa** October  7, 2021</sup>
<https://github.com/praveen-palanisamy/macad-agents/blob/b2726b391ee4f6844e2ae80883fb99f8027d34b4/Dockerfile#L103>

```bash
$ docker build --rm -f macad-agents/Dockerfile -t macad-agents:latest .
...

Step 8/15 : RUN conda install -y numpy
 ---> Running in 7123a03249d8
Solving environment: ...working...
```

No matter how many hours I wait, it stops as described above.</div>

**Comment by praveen-palanisamy** [comment]
Hi @rsuwa ,
Thank you for bringing this discussion item to my attention. I have responded to the discussion #17  and let's continue there since I believe this can be resolved without any code change on this repo.
