### ISSUE TITLE
is the continuous_a3c code valid?

### ISSUE THREAD

**Issue by Morphlng** [praveen-palanisamy/macad-agents#20]
I've tried the `continuous_A3C.py`, there exists some problems.

# Problem

## 1. Incorrect dictionary update

https://github.com/praveen-palanisamy/macad-agents/blob/b2726b391ee4f6844e2ae80883fb99f8027d34b4/src/macad_agents/a3c/continuous_A3C.py#L30-L33

Use `dict.update` to update a dictionary will override pre-exists keys in the dict, such as:

```python
(d1,d2) = ({"Country":{}},{"Country":{}})
d1['Country']['area'] = 960
d2['Country']['population'] = 14

d1.update(d2) # The 'area' key will be replaced by 'population'
```

This will cause the "fixed_delta_seconds" key to be lost, as a result macad-gym can't initialize.

## 2. Serialization Problem

https://github.com/praveen-palanisamy/macad-agents/blob/b2726b391ee4f6844e2ae80883fb99f8027d34b4/src/macad_agents/a3c/continuous_A3C.py#L145-L154

Putting environment inside Net is not a good idea, when mp.Process serialize this object, it will try to serialize the environment as well, resulting in "can't pickle pygame.Font object" error.

# Training

Even though I fixed those problems, it still doesn't seem to work. The "Mean Reward Curve" doesn't tend to go up (nor the distance curve to go down), and I haven't achieved one success episode yet (3M steps, maybe it's not enough to draw a conclusion?).

![pic1](https://user-images.githubusercontent.com/50166287/195532355-357ef831-0dd6-4f30-9de2-48fb863efd33.png)

I know that PPO and IMPALA are the recommended algorithms, but since A3C is available in the repo, I want to know if it actually works.

**Comment by SExpert12** [comment]
Hi, 
are you able to solve the problem in A3C algorithm?

**Comment by Morphlng** [comment]
> Hi, are you able to solve the problem in A3C algorithm?

No, the algorithm provided in this repo does not work out of the box. You can try to combine MACAD-Gym with MARLlib (or RLlib), we have successfully trained cooperative agent with MAPPO.

**Comment by SExpert12** [comment]
Okay. Thanks

**Comment by SExpert12** [comment]
Hi, @Morphlng 
I have seen you have worked so much on this repo. I am using this repo for multi-agent training. I don't understand how to visualize the training process in carla simulator.
Can you please guide me regarding this issue?
