### ISSUE TITLE
How to run baseline agent?

### ISSUE THREAD

**Issue by SHITIANYU-hue** [praveen-palanisamy/macad-agents#3]
I try to run the baseline agent according to this line,

python -m macad_agents.rllib.baseline_agent

But I found this error:

agents.baseline_agent
free(): invalid pointer
Aborted (core dumped)

**Comment by praveen-palanisamy** [comment]
Oh! Is that all the error message you get?
That's strange and too short to debug. It looks like some runtime issue.
Which CARLA server version are you using?

**Comment by SHITIANYU-hue** [comment]
I am using this version 'carla==0.9.4' actually, I follow the installation instruction from the macad_gym environment

**Comment by SHITIANYU-hue** [comment]
I can run this script successfully:
https://github.com/praveen-palanisamy/macad-gym/blob/master/examples/basic_agent.py

So I think my Carla version should be correct.

**Comment by praveen-palanisamy** [comment]
Okay. Let me try to reproduce your issue but,
```
free(): invalid pointer
Aborted (core dumped)
```
is too little information to understand what's going wrong. Do you have any insight or can you run it with a debugger (`pdb`/ `gdb`) and report with a verbose log?

**Comment by SHITIANYU-hue** [comment]
I just tried in debug mode, but still cannot find a detailed log. According to this discussion, 
https://stackoverflow.com/questions/56346569/free-invalid-pointer-aborted-core-dumped

Probably it's the problem of the macad-gym package?

**Comment by praveen-palanisamy** [comment]
That discussion in that stackoverflow link is on interoperability of PyTorch and Open3D. 
The `macad-gym` package doesn't use either of the packages.
The cause is still not identified. A PyTorch dev thought it may be with the incompatible CXX ABIs but it wasn't confirmed.

A stack trace or log from your system when it occurs is the way I can see how we can look deeper into this.

**Comment by SHITIANYU-hue** [comment]
Hello, thanks for your reply! Could you run the baseline agent successfully on your computer?

**Comment by praveen-palanisamy** [comment]
Yes!

Based on a quick debug, I think, I have found a hint at what's going wrong. It's likely with the `import carla` statement.
Can you try with a source install (`easy_install --user carla-0.9.4-py3.x-*.eg`)of the carla python package from [`carla/PythonAPI`](https://github.com/carla-simulator/carla/tree/master/PythonAPI)?

**Comment by SHITIANYU-hue** [comment]
Sure, I tried it on my computer, now it can launch the Carla simulator. But it still has new errors:

![image](https://user-images.githubusercontent.com/38762389/90988363-3a8a8880-e560-11ea-9bc5-5fdb5d6ffbe0.png)

**Comment by praveen-palanisamy** [comment]
Glad that the runtime issues is resolved for you!

This error is due to a minor change in the `macad-gym` library. 
You can change this line:
https://github.com/praveen-palanisamy/macad-agents/blob/5e0bf86e4175ffd3aabf52ac32016d4050da9cff/src/macad_agents/baseline_agent.py#L79

to: `vehicle_dict[actor_id] = env._actors[actor_i]`

(Just adding an underscore before `actors`)

**Comment by SHITIANYU-hue** [comment]
Thanks, I will try it. Besides, how can I run the code without a monitor?

**Comment by praveen-palanisamy** [comment]
For running without display/monitor, just the CARLA server needs to be launched in headless mode. 
The simplest way is to set the environment variable: `SDL_VIDEODRIVER=offscreen`. This may not work under all of the systems and configuration. But it's the best first try.

A sure-shot but more involved way is to set-up virtual GL and XVFB (X Virtual Frame Buffers) and use a dedicated Xorg X server to run in headless mode. If the necessary system packages are installed, `MACAD-Gym` will automatically launch the CARLA server in headless mode based if render is set to false in the config or when running with multiple GPUs and mutiple  sim environments

The containerized version will take care of this automatically. If you are running directly on the host, you may have to setup the system level packages yourself.
