### ISSUE TITLE
confusion about Baseline_agent

### ISSUE THREAD

**Issue by SHITIANYU-hue** [praveen-palanisamy/macad-agents#5]
Hello,
I run:
_python_ _baseline_agent.py_  by loading the environment jason file in the intersection environments:
[https://github.com/praveen-palanisamy/macad-gym/tree/master/src/macad_gym/envs/intersection](https://github.com/praveen-palanisamy/macad-gym/tree/master/src/macad_gym/envs/intersection)

But only one vehicle can be controlled. 
I also tried to run the baseline_agent with the default configuration. It is actually a single-vehicle drive straight forward. 

Here are my two confusions about the baseline agent:

1. How to control multi-agent?
As I saw in the source code:
` for actor_id in actor_configs.keys():
            vehicle_dict[actor_id] = env._actors[actor_id]`
I think it should be able to control multi-agent.

2. How to set the duration of the simulation?

If I want to let the agent run in a longer period(i.e. more time steps per episode), how to change the environment parameters.

Thanks and look forward to your reply

**Comment by praveen-palanisamy** [comment]
Which specific env config `.json` file are you using from [https://github.com/praveen-palanisamy/macad-gym/tree/master/src/macad_gym/envs/intersection](https://github.com/praveen-palanisamy/macad-gym/tree/master/src/macad_gym/envs/intersection)?

**Comment by praveen-palanisamy** [comment]
Note that all the environment configs currently in the repo are multi-agent environments and allows controlling each and every agent (manually or automatically).
In the [baseline_agent.py](https://github.com/praveen-palanisamy/macad-agents/blob/master/src/macad_agents/baseline_agent.py) script, a waypoint based `BasicAgent` is used to control all the (car) agents which likely drives the vehicles straight. The following lines are were the actions (vehicle control commands) are generated for each of the agent using the scripted, `BasicAgent`:

https://github.com/praveen-palanisamy/macad-agents/blob/3c6a1961113453443b0546f6556906796831fc0c/src/macad_agents/baseline_agent.py#L91-L95

You can modify the [baseline_agent.py](https://github.com/praveen-palanisamy/macad-agents/blob/master/src/macad_agents/baseline_agent.py) to use your own agent code to generate the actions.

**Comment by SHITIANYU-hue** [comment]
> Which specific env config `.json` file are you using from https://github.com/praveen-palanisamy/macad-gym/tree/master/src/macad_gym/envs/intersection?

Hi, I tried this one. [https://github.com/praveen-palanisamy/macad-gym/blob/master/src/macad_gym/envs/intersection/stop_sign_urban_intersection_3c.json](url)

As shown in the picture, the other vehicles don't move at all.


![image](https://user-images.githubusercontent.com/38762389/91380295-a2580200-e7f2-11ea-9894-a46f0f37290a.png)

**Comment by praveen-palanisamy** [comment]
@SHITIANYU-hue : Again, apologies for missing this until now.
I looked into your report and the config you were using has set [the following lines](https://github.com/praveen-palanisamy/macad-gym/blob/38884ac4bc7fb2e91a865950cff4eeadeed02f60/src/macad_gym/envs/intersection/stop_sign_urban_intersection_3c.json#L46-L47):

```json
                    "manual_control": false,
                    "auto_control": false,
```
For the car Actors which means, there's no control enabled and that' probably the reason 

Also, you can try the [`SimpleAgent` code](https://github.com/praveen-palanisamy/macad-gym#agent-interface) instead of the `baseline_agent` if that's easier to customize as per your needs.

**Comment by praveen-palanisamy** [comment]
Closing this issue. Feel free to re-open if you need more assistance.
