### ISSUE TITLE
ModuleNotFoundError: No module named 'env'

### ISSUE THREAD

**Issue by SHITIANYU-hue** [praveen-palanisamy/macad-agents#6]
In this script:
[https://github.com/praveen-palanisamy/macad-agents/blob/master/src/macad_agents/a3c/continuous_A3C_tune.py](url)
when i run ` python -m macad_agents.a3c.continuous_A3C_tune` i cannot find the env module.

**Comment by praveen-palanisamy** [comment]
Hi @SHITIANYU-hue ,
Thank you for reporting this! 
I have fixed the import error in #7 and I will merge it in soon. Please pull the changes and try again.
